before_script: 
    - sudo apt-get install ccache libffi-dev libicu-dev libgmp3-dev
    - ./configure --ccflags="-g"
script: "make test"
# branches:
#   only:
#     - master
notifications:
  recipients:
    - duke@leto.net
  email:
    on_success: change
    on_failure: always
