language: "perl"
perl:
    - "5.14"
install: "echo"
before_script:
    - sudo apt-get install libffi-dev libicu-dev libgmp3-dev clang llvm-dev zlib1g-dev gcc-multilib
    - cpanm -n LWP::UserAgent TAP::Harness::Archive TAP::Harness::ReportByDescription
    - gcc --version
    - g++ --version
    - clang --version
# This stuff used to be required, but was rolled into the Travis CI perl support.
#    - curl -L http://cpanmin.us | sudo perl - --self-upgrade
#    - export CI_USER=$USER
#    - mkdir ~/perl5 && perl -Mlocal::lib >> /tmp/local_lib_junk.sh && source /tmp/local_lib_junk.sh
#    - sudo chown -R $CI_USER ~/.cpanm
#    - sudo chown -R $CI_USER ~/perl5

script: "echo \"M0_INTERP=$M0_INTERP\"; perl Configure.pl $PARROT_CONFIG_ARGS $PARROT_OPTIMIZE --cc=\"$CC\" --link=\"$CC\" --ld=\"$CC\" --ccflags='-g' ; make $PARROT_TEST"

notifications:
  recipients:
    - parrot-ci@lists.parrot.org
    - duke@leto.net
  email:
    on_success: change
    on_failure: change
  irc:
    channels:
      - "irc.parrot.org#parrot"
    on_success: change
    on_failure: change
env:
    - M0_INTERP=./src/m0/c/m0              PARROT_CONFIG_ARGS="" PARROT_OPTIMIZE="--optimize" PARROT_TEST="m0_test" CC="clang"
    - M0_INTERP=./src/m0/perl/m0_interp.pl PARROT_CONFIG_ARGS="" PARROT_OPTIMIZE="--optimize" PARROT_TEST="m0_test" CC="clang"

    - PARROT_CONFIG_ARGS="" PARROT_OPTIMIZE=""           PARROT_TEST="codingstd_tests" CC="clang"
    - PARROT_CONFIG_ARGS="" PARROT_OPTIMIZE=""           PARROT_TEST="manifest_tests" CC="clang"
