language: "perl"
perl:
    - "5.18"
install: "echo"
before_script:
    - sudo apt-get install libffi-dev libicu-dev libgmp3-dev clang llvm-dev zlib1g-dev gcc-multilib
    - cpanm -n LWP::UserAgent TAP::Harness::Archive TAP::Harness::ReportByDescription
    - gcc --version
    - g++ --version
    - clang --version

script: "echo \"M0_INTERP=$M0_INTERP\"; perl Configure.pl $PARROT_CONFIG_ARGS $PARROT_OPTIMIZE --cc=\"$CC\" --link=\"$CC\" --ld=\"$CC\" --ccflags='-g' && make m0_debug && make \"$PARROT_TEST\""

notifications:
  recipients:
    - parrot-ci@lists.parrot.org
    - duke@leto.net
  email:
    on_success: change
    on_failure: change
  irc:
    channels:
      - "irc.parrot.org#parrot"
    on_success: change
    on_failure: change
env:
    - PARROT_CONFIG_ARGS="" PARROT_OPTIMIZE="" PARROT_TEST="m0_tests" CC="clang"
    - PARROT_CONFIG_ARGS="" PARROT_OPTIMIZE="" PARROT_TEST="m0_c_tests" CC="clang"
