before_script:
    - sudo apt-get install ccache libffi-dev libicu-dev libgmp3-dev clang
script: "perl Configure.pl --test=build $PARROT_OPTIMIZE --cc=\"$CC\" --link=\"$CC\" --ld=\"$CC\" --ccflags='-g' && make $PARROT_TEST"
# branches:
#   only:
#     - master
notifications:
  recipients:
    - duke@leto.net
  email:
    on_success: change
    on_failure: always
env:
    - PARROT_OPTIMIZE="--optimize" PARROT_TEST="fulltest" CC="clang"
    - PARROT_OPTIMIZE=""           PARROT_TEST="fulltest" CC="clang"
    - PARROT_OPTIMIZE="--optimize" PARROT_TEST="fulltest" CC="ccache gcc"
    - PARROT_OPTIMIZE="--optimize" PARROT_TEST="fulltest" CC="ccache g++"
    - PARROT_OPTIMIZE="--optimize" PARROT_TEST="fulltest" CC="gcc"
    - PARROT_OPTIMIZE="--optimize" PARROT_TEST="fulltest" CC="g++"
    - PARROT_OPTIMIZE=""           PARROT_TEST="fulltest" CC="ccache gcc"
    - PARROT_OPTIMIZE=""           PARROT_TEST="fulltest" CC="ccache g++"
    - PARROT_OPTIMIZE=""           PARROT_TEST="fulltest" CC="gcc"
    - PARROT_OPTIMIZE=""           PARROT_TEST="fulltest" CC="g++"
