language: "perl"
perl:
    - "5.14"
install: "echo"
before_script:
    - sudo apt-get install libffi-dev libicu-dev libgmp3-dev clang llvm-dev zlib1g-dev gcc-multilib
# No, we are not going to run the tests for all these dependencies on every commit
#    - cpanm -n LWP::UserAgent TAP::Harness::Archive TAP::Harness::ReportByDescription

script: "perl Configure.pl $PARROT_CONFIG_ARGS $PARROT_OPTIMIZE --cc=\"$CC\" --link=\"$CC\" --ld=\"$CC\" --ccflags='-g' ; make $PARROT_TEST"

branches:
   only:
     - master
notifications:
  recipients:
    - parrot-ci@lists.parrot.org
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "irc.parrot.org#parrot"
    on_success: change
    on_failure: change
env:
    - M0_INTERP=./src/m0/c/m0              PARROT_CONFIG_ARGS="" PARROT_OPTIMIZE="--optimize" PARROT_TEST="m0_test" CC="clang"
    - M0_INTERP=./src/m0/perl/m0_interp.pl PARROT_CONFIG_ARGS="" PARROT_OPTIMIZE="--optimize" PARROT_TEST="m0_test" CC="clang"
